### ISSUE TITLE
Pexpect error during migration

### ISSUE THREAD

**Issue by Pinkashia** [gglucass/AQUSA#8]
Command Executed: python3 manage.py db migrate
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pexpect/__init__.py", line 972, in read_nonblocking
    s = os.read(self.child_fd, size)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pexpect/__init__.py", line 1535, in expect_loop
    c = self.read_nonblocking(self.maxread, timeout)
  File "/usr/local/lib/python3.4/dist-packages/pexpect/__init__.py", line 977, in read_nonblocking
    raise EOF('End Of File (EOF). Exception style platform.')
pexpect.EOF: End Of File (EOF). Exception style platform.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from app import app, models, analyzers, db
  File "/home/ubuntu/AQUSA/AQUSA/app/__init__.py", line 14, in <module>
    from app import views, models
  File "/home/ubuntu/AQUSA/AQUSA/app/views.py", line 5, in <module>
    from .models import Stories, Projects, Defects
  File "/home/ubuntu/AQUSA/AQUSA/app/models.py", line 5, in <module>
    AQUSATagger = StanfordTagger()
  File "/home/ubuntu/AQUSA/AQUSA/app/taggers.py", line 11, in __init__
    self.pos_tagger.expect('done', timeout=20)
  File "/usr/local/lib/python3.4/dist-packages/pexpect/__init__.py", line 1451, in expect
    timeout, searchwindowsize)
  File "/usr/local/lib/python3.4/dist-packages/pexpect/__init__.py", line 1466, in expect_list
    timeout, searchwindowsize)
  File "/usr/local/lib/python3.4/dist-packages/pexpect/__init__.py", line 1554, in expect_loop
    raise EOF(str(err) + '\n' + str(self))
pexpect.EOF: End Of File (EOF). Exception style platform.
<pexpect.spawn object at 0x7fedb515ab38>
version: 3.3
command: /usr/bin/java
args: ['/usr/bin/java', '-mx300m', '-cp', 'stanford/stanford-postagger-withModel.jar', 'edu.stanford.nlp.tagger.maxent.MaxentTagger', '-model', 'stanford/english-left3words-distsim.tagger']
searcher: <pexpect.searcher_re object at 0x7fedb515af98>
buffer (last 100 chars): b''
before (last 100 chars): b's(ClassLoader.java:358)\r\n\tat sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)\r\n'
after: <class 'pexpect.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 18381
child_fd: 4
closed: False
timeout: 30
delimiter: <class 'pexpect.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
```

Postgresql list databases output (If this helps):

```
ubuntu@ip-xxx-xxx-xxx-xxx:~/AQUSA$ sudo -u postgres psql
psql (9.3.16)
Type "help" for help.

postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 aqusa     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
```

DATABASE_URL- "postgresql://postgres:ubuntu/localhost/aqusa"
Does anyone else faces this issue. Any help will be highly appreciated.

**Comment by gglucass** [comment]
Looks like you don't have java installed or pexpect doesn't know where to find the appropriate java runtime.

Please try to run the Stanford jar in isolation first ``stanford/stanford-postagger-withModel.jar``

**Comment by Pinkashia** [comment]
@gglucass, you are right, java was creating the error. But it was not with runtime location, it was with its version. I was using open-jdk7 earlier, now switched to open-jdk8 and the issue is fixed. But now I came across another error related flask itself. The exact traceback being:
```
ubuntu@ip-xxx-xxx-xxx-xxx:~/AQUSA/AQUSA$ python3 manage.py db migrate
Initialized StanfordTagger
creating catalog 'app/translations/en/LC_MESSAGES/messages.po' based on 'messages.pot'
compiling catalog 'app/translations/en/LC_MESSAGES/messages.po' to 'app/translations/en/LC_MESSAGES/messages.mo'
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    manager.run()
  File "/usr/local/lib/python3.4/dist-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python3.4/dist-packages/flask_script/__init__.py", line 350, in handle
    app_parser = self.create_parser(prog)
  File "/usr/local/lib/python3.4/dist-packages/flask_script/__init__.py", line 193, in create_parser
    command_parser = command.create_parser(name, func_stack=func_stack, parent=self)
AttributeError: 'NoneType' object has no attribute 'create_parser'
```
I checked the database and tables had already been created. This error occurs each time I ran any command involving manage.py
I googled about this and as per solutions the problem is with create command.
Any idea about how to resolve this?

**Comment by gglucass** [comment]
I think you should be able to already run the server by calling ``python3 run.py``

**Comment by Pinkashia** [comment]
Thanks, @gglucass, I am able to ran the server using run script.

On the side note, I think the manage.py should ran as well as I followed the proper set-up procedure. Do you think there is something I missed during set-up, a component or a library, which might be causing the issue.

Also, the app reports an error while creating new project. I try to debug the code found one minor mistake in `app/models.py` file on `line 102`
The class name is `Projects` but constructor being used is `Project`. I made this change and project got created.

Please update this file in your repo as well.

**Comment by gglucass** [comment]
Hi Pinkashia,

The issue with manage.py is known and still on my to-do list for resolving. Unfortunately, I've got 0 time to put into this for the time being.

Interesting that that error occurs with `models.py` - it might have to do with a slightly different version of Flask or something. I'll take a closer look at some point :-)

**Comment by Pinkashia** [comment]
Okay. Thanks for helping me set this up.
For the models.py error, I don't think the Flask version is creating an issue here. There are many classes in models.py, all with their constructors correctly initialised. 
I guess this Project constructor might be modified unknowingly and pushed to the master. 
Anyway, I am able to create a new project with the correction and can proceed with my research.

Thanks again for your time. Cheers!
